# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='名称')),
                ('nick_name', models.CharField(default='', max_length=20, unique=True, verbose_name='ID')),
                ('age', models.CharField(default='', max_length=20, verbose_name='年龄')),
                ('nationality', models.CharField(default='', max_length=10, verbose_name='国籍')),
                ('team', models.CharField(default='', max_length=10, verbose_name='战队')),
                ('intro', models.TextField(default='', verbose_name='简介')),
                ('playerImage', models.FilePathField(default='', path='/usr/DjangoProjects/dotaplayers/images')),
                ('slug', models.CharField(default='', max_length=256, verbose_name='网址')),
            ],
            options={
                'verbose_name_plural': '选手',
                'verbose_name': '选手',
            },
        ),
    ]
