# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('author', models.CharField(max_length=25, verbose_name='作者')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('slug', models.CharField(db_index=True, max_length=120, verbose_name='网址')),
                ('player', models.ManyToManyField(to='player.Player', verbose_name='归属选手')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=25, verbose_name='视频名称')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('slug', models.CharField(max_length=256, verbose_name='视频网址')),
                ('player', models.ManyToManyField(to='player.Player', verbose_name='归属选手')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
            },
        ),
    ]
