# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_news_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='playerImage',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
