# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20160514_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='player',
        ),
    ]
