# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_remove_news_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='player',
        ),
        migrations.AddField(
            model_name='video',
            name='videoslug',
            field=models.CharField(default='', max_length=256, verbose_name='视频网址'),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.CharField(default='', max_length=120, verbose_name='网址'),
        ),
    ]
