# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_auto_20160515_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_name',
            field=models.CharField(default='', max_length=25, verbose_name='视频名称'),
        ),
    ]
