# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_auto_20160521_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(default='', verbose_name='内容'),
        ),
    ]
