# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 11:13
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0010_auto_20160521_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='player',
            name='intro',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='简介'),
        ),
    ]
