# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_auto_20160521_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_title', models.CharField(default='', max_length=25, verbose_name='直播间名称')),
                ('live_slug', models.CharField(default='', max_length=256, verbose_name='直播间网址')),
                ('slug', models.CharField(default='', max_length=120, verbose_name='网址')),
                ('home_display', models.BooleanField(default=False, verbose_name='首页显示')),
                ('live_player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='归属选手')),
            ],
            options={
                'verbose_name_plural': '视频',
                'verbose_name': '直播',
            },
        ),
    ]
