# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0013_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='live_img',
            field=models.CharField(default='', max_length=256, verbose_name='直播间缩略图'),
        ),
    ]
