# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0014_live_live_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='live_player',
            field=models.CharField(default='', max_length=20, verbose_name='直播间所属选手'),
        ),
    ]
